# Generated by Django 5.1 on 2024-10-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tset', '0002_moneymakeruser_venue_event_attendees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='nmd46348559193224090',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('number', models.IntegerField()),
                ('qTitMeDem', models.IntegerField()),
                ('zOrdMeDem', models.IntegerField()),
                ('pMeDem', models.IntegerField()),
                ('pMeOf', models.IntegerField()),
                ('zOrdMeOf', models.IntegerField()),
                ('qTitMeOf', models.IntegerField()),
            ],
        ),
    ]
